import { useState, useCallback } from 'react';
import { createContainer } from 'react-tracked';
import produce from 'immer';


const repositories = [
    {
        "id": 336777,
        "node_id": "MDEwOlJlcG9zaXRvcnkzMzY3Nzc=",
        "name": "samples",
        "full_name": "angular/samples",
        "private": false,
        "owner": {
            "login": "angular",
            "id": 139426,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTQyNg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/139426?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/angular",
            "html_url": "https://github.com/angular",
            "followers_url": "https://api.github.com/users/angular/followers",
            "following_url": "https://api.github.com/users/angular/following{/other_user}",
            "gists_url": "https://api.github.com/users/angular/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/angular/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/angular/subscriptions",
            "organizations_url": "https://api.github.com/users/angular/orgs",
            "repos_url": "https://api.github.com/users/angular/repos",
            "events_url": "https://api.github.com/users/angular/events{/privacy}",
            "received_events_url": "https://api.github.com/users/angular/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "html_url": "https://github.com/angular/samples",
        "description": "DEPRICATED",
        "fork": false,
        "url": "https://api.github.com/repos/angular/samples",
        "forks_url": "https://api.github.com/repos/angular/samples/forks",
        "keys_url": "https://api.github.com/repos/angular/samples/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/angular/samples/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/angular/samples/teams",
        "hooks_url": "https://api.github.com/repos/angular/samples/hooks",
        "issue_events_url": "https://api.github.com/repos/angular/samples/issues/events{/number}",
        "events_url": "https://api.github.com/repos/angular/samples/events",
        "assignees_url": "https://api.github.com/repos/angular/samples/assignees{/user}",
        "branches_url": "https://api.github.com/repos/angular/samples/branches{/branch}",
        "tags_url": "https://api.github.com/repos/angular/samples/tags",
        "blobs_url": "https://api.github.com/repos/angular/samples/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/angular/samples/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/angular/samples/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/angular/samples/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/angular/samples/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/angular/samples/languages",
        "stargazers_url": "https://api.github.com/repos/angular/samples/stargazers",
        "contributors_url": "https://api.github.com/repos/angular/samples/contributors",
        "subscribers_url": "https://api.github.com/repos/angular/samples/subscribers",
        "subscription_url": "https://api.github.com/repos/angular/samples/subscription",
        "commits_url": "https://api.github.com/repos/angular/samples/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/angular/samples/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/angular/samples/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/angular/samples/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/angular/samples/contents/{+path}",
        "compare_url": "https://api.github.com/repos/angular/samples/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/angular/samples/merges",
        "archive_url": "https://api.github.com/repos/angular/samples/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/angular/samples/downloads",
        "issues_url": "https://api.github.com/repos/angular/samples/issues{/number}",
        "pulls_url": "https://api.github.com/repos/angular/samples/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/angular/samples/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/angular/samples/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/angular/samples/labels{/name}",
        "releases_url": "https://api.github.com/repos/angular/samples/releases{/id}",
        "deployments_url": "https://api.github.com/repos/angular/samples/deployments",
        "created_at": "2009-10-14T04:35:36Z",
        "updated_at": "2020-09-20T18:12:59Z",
        "pushed_at": "2010-01-14T00:09:02Z",
        "git_url": "git://github.com/angular/samples.git",
        "ssh_url": "git@github.com:angular/samples.git",
        "clone_url": "https://github.com/angular/samples.git",
        "svn_url": "https://github.com/angular/samples",
        "homepage": "http://www.getangular.com",
        "size": 93,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "Ruby",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": true,
        "forks_count": 13,
        "mirror_url": null,
        "archived": true,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 13,
        "open_issues": 0,
        "watchers": 1,
        "default_branch": "master",
        "permissions": {
            "admin": false,
            "push": false,
            "pull": true
        }
    },
    {
        "id": 460078,
        "node_id": "MDEwOlJlcG9zaXRvcnk0NjAwNzg=",
        "name": "angular.js",
        "full_name": "angular/angular.js",
        "private": false,
        "owner": {
            "login": "angular",
            "id": 139426,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTQyNg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/139426?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/angular",
            "html_url": "https://github.com/angular",
            "followers_url": "https://api.github.com/users/angular/followers",
            "following_url": "https://api.github.com/users/angular/following{/other_user}",
            "gists_url": "https://api.github.com/users/angular/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/angular/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/angular/subscriptions",
            "organizations_url": "https://api.github.com/users/angular/orgs",
            "repos_url": "https://api.github.com/users/angular/repos",
            "events_url": "https://api.github.com/users/angular/events{/privacy}",
            "received_events_url": "https://api.github.com/users/angular/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "html_url": "https://github.com/angular/angular.js",
        "description": "AngularJS - HTML enhanced for web apps!",
        "fork": false,
        "url": "https://api.github.com/repos/angular/angular.js",
        "forks_url": "https://api.github.com/repos/angular/angular.js/forks",
        "keys_url": "https://api.github.com/repos/angular/angular.js/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/angular/angular.js/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/angular/angular.js/teams",
        "hooks_url": "https://api.github.com/repos/angular/angular.js/hooks",
        "issue_events_url": "https://api.github.com/repos/angular/angular.js/issues/events{/number}",
        "events_url": "https://api.github.com/repos/angular/angular.js/events",
        "assignees_url": "https://api.github.com/repos/angular/angular.js/assignees{/user}",
        "branches_url": "https://api.github.com/repos/angular/angular.js/branches{/branch}",
        "tags_url": "https://api.github.com/repos/angular/angular.js/tags",
        "blobs_url": "https://api.github.com/repos/angular/angular.js/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/angular/angular.js/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/angular/angular.js/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/angular/angular.js/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/angular/angular.js/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/angular/angular.js/languages",
        "stargazers_url": "https://api.github.com/repos/angular/angular.js/stargazers",
        "contributors_url": "https://api.github.com/repos/angular/angular.js/contributors",
        "subscribers_url": "https://api.github.com/repos/angular/angular.js/subscribers",
        "subscription_url": "https://api.github.com/repos/angular/angular.js/subscription",
        "commits_url": "https://api.github.com/repos/angular/angular.js/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/angular/angular.js/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/angular/angular.js/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/angular/angular.js/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/angular/angular.js/contents/{+path}",
        "compare_url": "https://api.github.com/repos/angular/angular.js/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/angular/angular.js/merges",
        "archive_url": "https://api.github.com/repos/angular/angular.js/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/angular/angular.js/downloads",
        "issues_url": "https://api.github.com/repos/angular/angular.js/issues{/number}",
        "pulls_url": "https://api.github.com/repos/angular/angular.js/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/angular/angular.js/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/angular/angular.js/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/angular/angular.js/labels{/name}",
        "releases_url": "https://api.github.com/repos/angular/angular.js/releases{/id}",
        "deployments_url": "https://api.github.com/repos/angular/angular.js/deployments",
        "created_at": "2010-01-06T00:34:37Z",
        "updated_at": "2021-02-24T06:13:44Z",
        "pushed_at": "2021-02-06T21:18:15Z",
        "git_url": "git://github.com/angular/angular.js.git",
        "ssh_url": "git@github.com:angular/angular.js.git",
        "clone_url": "https://github.com/angular/angular.js.git",
        "svn_url": "https://github.com/angular/angular.js",
        "homepage": "https://angularjs.org",
        "size": 101103,
        "stargazers_count": 59589,
        "watchers_count": 59589,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 28570,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 467,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "forks": 28570,
        "open_issues": 467,
        "watchers": 59589,
        "default_branch": "master",
        "permissions": {
            "admin": false,
            "push": false,
            "pull": true
        }
    }
]

const contributors = [
    {
        "login": "petebacondarwin",
        "id": 15655,
        "node_id": "MDQ6VXNlcjE1NjU1",
        "avatar_url": "https://avatars.githubusercontent.com/u/15655?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/petebacondarwin",
        "html_url": "https://github.com/petebacondarwin",
        "followers_url": "https://api.github.com/users/petebacondarwin/followers",
        "following_url": "https://api.github.com/users/petebacondarwin/following{/other_user}",
        "gists_url": "https://api.github.com/users/petebacondarwin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/petebacondarwin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/petebacondarwin/subscriptions",
        "organizations_url": "https://api.github.com/users/petebacondarwin/orgs",
        "repos_url": "https://api.github.com/users/petebacondarwin/repos",
        "events_url": "https://api.github.com/users/petebacondarwin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/petebacondarwin/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 1591,
        "followers": 50,
        "repos": 120,
        "gists": 10
    },
    {
        "login": "gkalpak",
        "id": 8604205,
        "node_id": "MDQ6VXNlcjg2MDQyMDU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/8604205?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gkalpak",
        "html_url": "https://github.com/gkalpak",
        "followers_url": "https://api.github.com/users/gkalpak/followers",
        "following_url": "https://api.github.com/users/gkalpak/following{/other_user}",
        "gists_url": "https://api.github.com/users/gkalpak/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gkalpak/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gkalpak/subscriptions",
        "organizations_url": "https://api.github.com/users/gkalpak/orgs",
        "repos_url": "https://api.github.com/users/gkalpak/repos",
        "events_url": "https://api.github.com/users/gkalpak/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gkalpak/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 1541,
        "followers": 150,
        "repos": 220,
        "gists": 10
    }
];


const initialState = {
    repositories: [...repositories],
    contributors: [...contributors],
    dropdownToggle: false
};

const useValue = () => useState(initialState);

const { Provider, useTrackedState, useUpdate: useSetState } = createContainer(
  useValue,
);

const useSetDraft = () => {
  const setState = useSetState();
  return useCallback(
    draftUpdater => {
      setState(produce(draftUpdater));
    },
    [setState],
  );
};

export { Provider, useTrackedState, useSetDraft };